[workspace]

resolver = "2"

members = [
    "day_1a",
    "day_1b",
    "day_2a",
    "day_2b",
    "day_3a",
    "day_3b",
    "day_4a",
    "day_4b",
    "day_5a",
    "day_5b",
    "day_6a",
    "day_6b",
    "day_7a",
    "day_7b",
]
